[package]
name = "utxorpc"
version = "1.0.0-alpha.1"
edition = "2021"
description = "UTxO RPC SDK"
repository = "https://github.com/utxorpc/rust-sdk"
homepage = "https://github.com/utxorpc/rust-sdk"
documentation = "https://docs.rs/utxorpc"
license = "Apache-2.0"
readme = "README.md"
authors = ["Santiago Carmuega <santiago@carmuega.me>"]

[dependencies]
utxorpc-spec = "0.3.0"
